### PR TITLE
Remove all plugins

### PR DESCRIPTION
**Pull request by daffl**
This pull requests removes all non-core plugins for CanJS 3.0. Plugins have been migrated to their own repositories and modules in the CanJS organization.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
@daffl I was thinking super should be core.  What do you think?

**Comment by daffl** [comment]
Should it not be a plugin at all then?

**Comment by justinbmeyer** [comment]
What do you mean by plugin?  If you mean should it be in its own modlet, then yes it should.  Its still a good practice to have things broken out.

**Comment by daffl** [comment]
Makes sense. I added it back in. All other plugins have been removed and now live in their own repository.

**Pull request merged**
