### PR TITLE
adds a deprecation warning for can.mustache

### LINKED ISSUE #1638: Mark `can.mustache` as deprecated & add note to `can.Component`
With the memory leak fixes that were made to `can.Component` as they relate to `can.stache` exclusively - we have officially turned out backs on `can.mustache`. We should put a deprecated tag on it in the API and perhaps a note on `can.Component` urging people that if they intend to use components then they should use `can.stache` instead, otherwise there is the potential for bad memory leaks.

### PR DESCRIPTION
**Pull request by moschel**
fixes #1638 

screenshot 2015-05-02 22 15 01

### CODE REVIEW

**Comment by daffl** [comment]
@James0x57 wrote a migration script for this. Before putting this warning in we should polish it, add documentation and link to it.

**Comment by moschel** [comment]
@James0x57 is this script done? Can you point to where it is?

**Comment by James0x57** [comment]
Hey Guys, here is the script:
https://github.com/canjs/can-upgrade/blob/master/bin/mustache_to_stache.js

There is one TODO note in there I'd like to address when I have time, and I should probably remove the string prototype getters I did for colors and do them another way, but it all works as is.

$ cd /root/of/your/project
$ npm install can-upgrade
$ node /node_modules/can-upgrade/bin/mustache_to_stache.js .

**Comment by daffl** [comment]
It would be great if you could add some quick documentation in the Readme so that we can link it in the deprecation warning.

**Comment by julia-allyce** [comment]
@James0x57 are we ok to link to can-upgrade yet? If not, I think we should merge this PR so there is at least a notice in for mustache.

**Comment by James0x57** [comment]
@julia-allyce should be fine to link to

**Comment by pYr0x** [comment]
i think we can close this.
there is a deprecated warning and a link to can-upgrade

**Pull request closed without merging**
