### PR TITLE
Listen to object changes in the `each` helper.

### PR DESCRIPTION
**Pull request by garrettreed**
For #2318.

Add a compute for listening to object changes in the each helper.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Probably don't want to run the compute

**Comment by garrettreed** [comment]
> Probably don't want to run the compute

Yeah, this probably isn't the best way to go about it, but it seems to work. Not running it breaks other tests.

**Comment by justinbmeyer** [comment]
I'll be online in about 20. I can help you out with it then.

**Comment by garrettreed** [comment]
@justinbmeyer this is ready to be merged and #2318 can be closed.

**Pull request closed without merging**
