### PR TITLE
Really add can-observe to ecosystem

### PR DESCRIPTION
**Pull request by imaustink**
Closes canjs/can-observe#7

### CODE REVIEW

**Comment by matthewp** [comment]
Are the doc links and github stars stuff added?

**Comment by imaustink** [comment]
@matthewp they are now

**Comment by matthewp** [comment]
@imaustink I think you need to wrap the require() in the test in an if statement, checking for `typeof Proxy === "function"`

**Comment by imaustink** [comment]
@phillipskevin should I base this off `minor` instead of `master` then?

**Comment by phillipskevin** [comment]
why do you need to update the other dependencies? it would be nice to get this in now instead of waiting until we're ready for 3.12.0.

**Comment by imaustink** [comment]
The build won't pass without upgrading those deps. Mostly upgrading just removed `can-util/log` and `can-util/dev` but I think there was a least 1 other fix as well.

**Comment by phillipskevin** [comment]
Ok, then can you point this to the `minor` branch instead? We can try to get a `3.12.0` out tomorrow or early next week.

**Pull request merged**
