### PR TITLE
Fixing FF debugging functions conflicting with Can Map and Event functions

### PR DESCRIPTION
**Pull request by tracer99**
FF introduced a debugging function called watch. This meant that if you had a property labeled watch, it would throw an exception.

### CODE REVIEW

**Comment by daffl** [comment]
This looks good. Two things: Could you squash your commits and can we add test that breaks in Firefox for this?

**Comment by tracer99** [comment]
Arghh. It appears I made it worse. At this point my git skills have been exhausted.

**Comment by daffl** [comment]
Oh no. I can look into it if you can provide a breaking test for Firefox. Thinking more about it I am not sure if always checking for `hasOwnProperty` is the right solution yet so I'd like to double check it.

**Comment by tracer99** [comment]
https://gitter.im/bitovi/canjs?at=55e870c9d231aa8e5918fdbd Matthew agrees that this may not be the best solution either.

To have this fail in FF, simply change any of the tests you have already by replacing the key name with "watch" and it will fail in modern FF.

**Comment by julia-allyce** [comment]
@tracer99 I am going to close this PR, and open an new issue for this. Would love to implement your contribution if you wanted to create a fresh PR with your fix and/or failing test.

**Pull request closed without merging**
