### PR TITLE
Upgrade to can-simple-dom 0.3.0

### PR DESCRIPTION
**Pull request by matthewp**
This is needed to release donejs 0.7.0

### CODE REVIEW

**Comment by daffl** [comment]
I don't think this is necessary. `^0.3.0-pre.0` should match every `0.3.x` release (tested with http://semver.npmjs.com/)

**Comment by matthewp** [comment]
That only happens on fresh npm installs though, right? I think of someone did an `npm update` they wouldn't be upgraded.

**Comment by daffl** [comment]
I just tested `npm update` on my local CanJS. Before:

```
can-simple-dom@0.3.0-pre.3
```

After:

```
can-simple-dom@0.3.0
```

So it seems to work.

**Comment by daffl** [comment]
We'll get the correct version range into the next release

**Pull request merged**
