### PR TITLE
Use regular 'routeUrl' helper syntax in can-href deprecation notice.

### PR DESCRIPTION
**Pull request by m-mujica**

### CODE REVIEW

**Comment by matthewp** [comment]
I've been just using it like a normal helper:

```
href="{{routeUrl page='orders'}}"
```

**Comment by justinbmeyer** [comment]
Yeah, the `normal helper` is what we ended up promoting now.

**Comment by m-mujica** [comment]
@matthewp @justinbmeyer I like the 'regular helper' version better, I changed the deprecation notice to read like:

'Use the routeUrl helper like `href={{routeUrl prop=value}}`'

Is that better?

**Comment by matthewp** [comment]
Yep, thank!

**Pull request merged**
