### PR TITLE
Landscaper: "canjs-docs-import-export" services

### PR DESCRIPTION
**Pull request by roemhildtg**
This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:

1. **https://gist.github.com/roemhildtg/1aad302cabe76add0f29804d0c6dfb91**

Please review this PR carefully as Landscaper does not guarantee any code mod's quality.

### CODE REVIEW

**Comment by roemhildtg** [comment]
https://regex101.com/r/iZdrAM/2

**Comment by matthewp** [comment]
Nice!

**Comment by matthewp** [comment]
Can you submit this against the `major` branch? That's most likely where we'll make the change.

**Comment by roemhildtg** [comment]
I changed the branch to major, is that what you meant? Or should I re-run the landscaper against the major branch?

**Comment by matthewp** [comment]
Yeah, rerun against the major branch. Sorry :( I should have specified this before.

**Comment by roemhildtg** [comment]
No worries! Its super easy now that there's a landscaper gist.

**Pull request closed without merging**
