### PR TITLE
add idKey for fixtures

### PR DESCRIPTION
**Pull request by uzlov**
Functionality for add idKey for fixtures

### CODE REVIEW

**Comment by julia-allyce** [comment]
Hey @uzlov can you provide some context for this PR? Is there an issue that this relates to?

**Comment by uzlov** [comment]
we will have functionality more the same with models (in my case - I use id for caching)

**Comment by pYr0x** [comment]
@uzlov can you please create a test and check the CI failure

**Comment by pYr0x** [comment]
we have [can-fixture](https://github.com/canjs/can-fixture) 0.3.0 and can-set
close this

**Comment by justinbmeyer** [comment]
```js
var algebra = set.Algebra(
  set.comparators.id('_id')
};

var store = fixture.store([{_id: 5, ...},..], algebra);
fixture("/something/{_id}", store)
```

**Pull request closed without merging**
