### PR TITLE
Remove access to `viewModel` property on the element from docs

### LINKED ISSUE #5138: Update docs for access `viewModel` on the element
We currently show accessing `viewModel` property on the element, with the new `StacheDefineElement` the element is the observable so there is no need to use the `viewModel` property.

```js
const appVM = window.appVM = document.querySelector("todo-mvc").viewModel;
```

Would be:
```js
const appVM = window.appVM = document.querySelector("todo-mvc");
```

We use these in the following guides:

- https://canjs.com/doc/guides/recipes/cta-bus-map.html#Changetheapptitle
- https://canjs.com/doc/guides/recipes/tinder-carousel.html#Showthecurrentandnextprofileimages
- https://canjs.com/doc/guides/todomvc.html#Defineandusethemaincomponent
- https://canjs.com/doc/guides/routing.html#Overview

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #5138

### CODE REVIEW

**Comment by m-mujica** [comment]
should I also update stuff like:

```js
events: {
  click() {
      this.viewModel.visible = !this.viewModel.visible;
   }
}
```

or will the codemods take care of `this.viewModel` references? @Mattchewone @phillipskevin

**Comment by matthewp** [comment]
These need to be converted to use `StacheElement` as well.

**Comment by m-mujica** [comment]
hmm got it, should I just use the codemod? I thought that was part of a different issue?

**Comment by matthewp** [comment]
You can use the codemod or do it manually, but I don't think we should merge changes that result in the demo being broken (even if being fixed later).

**Comment by m-mujica** [comment]
roger that

**Comment by Mattchewone** [comment]
Pretty sure the codemods won't change those references.

**Comment by phillipskevin** [comment]
We can do the codemods as part of https://github.com/canjs/canjs/issues/5119.

**Pull request merged**
