### PR TITLE
%root property is serialized when can.Map instance is shared between a component viewModel and a can.route

### LINKED ISSUE #2080: %root property is serialized when can.Map instance is shared between a component viewModel and a can.route
if you create a `can.Map` instance, and supply it to a component, then to `can.route`, you will get a `%root` property serialized into your route..

I worked around by adding a define block with `serialize : false` to the aforementioned Map instance, but should this property be defaulted to `serialize : false` some way?

### PR DESCRIPTION
**Pull request by prashantsharmain**
Fixes #2080

### CODE REVIEW

**Comment by daffl** [comment]
Thank you! It looks like JSHint failed (you should see the same error if you run `npm test`). Also, I think if you are not using the define plugin you will still get the `%root` property serialized. It may need to be added to https://github.com/canjs/canjs/blob/master/map/map_helpers.js#L75 as well.

**Comment by justinbmeyer** [comment]
@prashantsharmain did you try the solution I posted in the issue: 

```
var oldSerialize = viewModel.serialize;
viewModel.serialize = function(){
    var result = oldSerialize.apply(this, arguments);
    delete result["%root"];
    return result;
}
```

putting that in can.Component should fix the problem no matter what.

**Comment by prashantsharmain** [comment]
@daff @justinbmeyer I have fixed the jshint error, but I'm having problems running grunt test on my machine:

c:\projects\canjs>grunt test
Loading "changelog.js" tasks...ERROR
>> Error: Cannot find module 'oauth-sign'
Loading "docco.js" tasks...ERROR
>> Error: Cannot find module 'docco'
Loading "build.js" tasks...ERROR
>> Error: Cannot find module 'winston'
Loading "export.js" tasks...ERROR
>> Error: Cannot find module 'jsonfile'
Loading "live-reload.js" tasks...ERROR
>> Error: Cannot find module 'chokidar'
Cannot find module 'brace-expansion'
Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\projects\canjs\node_modules\fileset\node_modules\minimatch\minimatch.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Loading "testee.js" tasks...ERROR
>> Error: Could not register command from file check-coverage.js
Warning: Task "testee" not found. Use --force to continue.

Aborted due to warnings.

When I try running tests in browser by pointing to http://localhost:8000/test/, all the tests pass. My observations:
- I see 5 iframes, but only 3 test suites are executed: CanJS jQuery tests, CanJS jQuery (2.x) tests, CanJS YUI tests. The other 2 iframes stay blank.
- I don't see the jshint error here at all. I see all test cases passing in the 3 iframes.

Am I missing something here?

**Comment by matthewp** [comment]
I never run grunt test locally because it's too flaky. I test in browsers and then let Travis handle running it with Phantom.  I'd start by fixing the jshint problem from here: https://travis-ci.org/canjs/canjs/jobs/94478367#L617

Also, if not all 5 test suites are running that's likely an issue.  You can run an individual one, like mootools, by opening test/mootools.html

**Comment by prashantsharmain** [comment]
@daffl Is this good to be merged now? Sorry it took me a long time to get the tests running on my machine.

**Comment by daffl** [comment]
Yes, that looks great. Thank you!
What issues did you have with the tests? Maybe there's something we can do to make it easier.

**Pull request merged**
