### PR TITLE
fix #1541 can.Component should show a warning if tag name is missing a hyphen

### LINKED ISSUE #1541: can.Component should show a warning if tag name is missing a hyphen
Currently stache fails silently and does not render the template if a component's tag is missing a hyphen. The user should be notified with a warning if the tag is missing the hyphen.

### PR DESCRIPTION
**Pull request by cherifGsoul**
fix #1541

### CODE REVIEW

**Comment by cherifGsoul** [comment]
@daffl can you see why the build fail? I tried to correct the test but it dosent work in my computer the ```npm test``` pass like a charm

**Comment by cherifGsoul** [comment]
@justinbmeyer Can you tell me please why the build dosent work?

**Comment by justinbmeyer** [comment]
https://travis-ci.org/canjs/canjs/jobs/115994897#L1717

That's the test that is breaking.

**Comment by cherifGsoul** [comment]
@justinbmeyer @daffl this can be merged

**Comment by pYr0x** [comment]
@justinbmeyer can we merge that, or should that PR in https://github.com/canjs/can-stache ?

**Comment by justinbmeyer** [comment]
Better in can-stache

**Comment by cherifGsoul** [comment]
Ok I will make it in can-stache

**Comment by pYr0x** [comment]
@cherifGsoul thanks... i will merge then...

**Comment by pYr0x** [comment]
i think this is a good update for legacy canjs 2.3

**Pull request merged**
