### PR TITLE
docs(guides): Comparison - section comparing CanJS with RxJS (observables)

### PR DESCRIPTION
**Pull request by BigAB**
Part of #2679

### CODE REVIEW

**Comment by BigAB** [comment]
Well, I don't think this is going to get merged anymore.


...also the examples are out of date.  maybe next time.

**Comment by justinbmeyer** [comment]
We still plan to get an updated version in.

**Comment by BigAB** [comment]
You see the date on this right?

Does this pull request bring you joy?
If you answer yes, you keep it open.

If you hesitate or say no, thank it for the service it has provided, then close it.

**Comment by justinbmeyer** [comment]
Yes. Maybe I like pain.

**Comment by chasenlehara** [comment]
I’m merging this as-is because we’re not linking to the comparison page from anywhere and this can help the next person who works on that page.

**Pull request merged**
