### PR TITLE
Add ReactViewModel

### PR DESCRIPTION
**Pull request by christopherjbaker**
I added the shrinkwrapped dependencies, modified the docs glob, and incorporated the tests.

### CODE REVIEW

**Comment by christopherjbaker** [comment]
Current test failures are fixed in canjs/can-stache-converters#34

**Comment by justinbmeyer** [comment]
@m-mujica / @matthewp it seems that `process` isn't provided anymore to the built files.  Can you take a look at this?

**Comment by matthewp** [comment]
Are you talking about what is loaded by test/index.html? That loads can.all.js, which is a global exported build. As far as I remember the global shim never had `process`, only the steal npm plugin (which does still have it). I'm not opposed to adding it to the global shim though.

**Comment by matthewp** [comment]
I don't understand how this is supposed to work.  There are several libs being ignored in the build: https://github.com/canjs/canjs/blob/master/build.js#L6-L7 . but there are no corresponding script tags for those libs in the text HTML pages. So I don't understand how those libs are not throwing.

**Comment by matthewp** [comment]
Digging into it more it looks like, in the example of can-stream-kefir, that kefir is excluded from the build and is not on the window, but because can-stream-kefir doesn't care in the module body if `Kefir` is undefined, it doesn't break. But it would break if someone attempted to use it (although I'm not quite sure how they would do so).

**Comment by matthewp** [comment]
So I think we need to either include react and all of its dependencies into the build or exclude it, and react-view-model and can-react-component. For now I'm not to exclude those.

**Comment by justinbmeyer** [comment]
Yeah, we should do it like kefir and jQuery ... not include them in the build, while allowing the build to work without them (at least the modules that don't depend on them).

I know for jQuery, we do this conditionally a few places. We test that the jQuery module actually provided a value.

**Pull request merged**
