### PR TITLE
Switch CanJS from steal to CommonJS

### PR DESCRIPTION
**Pull request by BigAB**
Tried not to alter any functionality while doing so, but tried to remove the `steal` sytax entirely from CanJS source

### CODE REVIEW

**Comment by Bajix** [comment]
You sir are a saint. That is all. 
:+1:

**Comment by daffl** [comment]
:boom:

**Comment by cherifGsoul** [comment]
a ncie one thank you for this :+1:

**Comment by daffl** [comment]
This has been published as CanJS `v3.0.0-pre.0` (you can get it via `npm install can@furiosa`).

**Pull request merged**
