### PR TITLE
#2444 autorender did not attach vm to the element

### PR DESCRIPTION
**Pull request by ilyavf**
Attach VM to the autorender element when creating a new one.

### CODE REVIEW

**Comment by matthewp** [comment]
Can you add a test?

**Comment by matthewp** [comment]
can/map/app doesn't have any use any more and should be removed. Use can/map here instead.  In 3.0 it will need to be types.DefaultMap.

**Comment by ilyavf** [comment]
@matthewp I removed can/map/app usage, so its back to pre-[39c08a](https://github.com/canjs/canjs/commit/39c08a421c21f7343fa41c88fdb7caaaae141e31) state:
```
// This will create a new scope (if it does not exist) and attach it to `el` with data:
var scope = can.viewModel(el);
```
Tests are there.

**Comment by matthewp** [comment]
Failing in Travis, is it working locally?

**Comment by ilyavf** [comment]
@matthewp Locally I am getting stuck on amd tests (4159 - on the same test as Travis)
```
Running "testee:steal" (testee) task
....... 
22850 passing (4m)
Running "testee:amd" (testee) task
... 4159 dots ... and stuck
```

**Comment by ilyavf** [comment]
@matthewp: Woohoo, the CI is passing. So, I had to import `can/map/app` from inside autorender.js. Do you have an idea why?

**Comment by matthewp** [comment]
No, can/map/app should be removed actually. So there must be something wrong here. Which test is failing without it?

**Comment by matthewp** [comment]
We can fix can/map/app in another issue, or not at all since can-view-autorender doesn't depend on it.

**Pull request merged**
