### PR TITLE
Fix can.batch.stop() to call ALL callbacks

### PR DESCRIPTION
**Pull request by UselessPickles**
Fixes this issue:  https://github.com/canjs/canjs/issues/3285

### CODE REVIEW

**Comment by UselessPickles** [comment]
I'm sure it's obvious, but I'm new to github and contributing to this project. I clearly am not doing something right because my simple "move a line and add a comment" change is failing automated tests. Looks like it's probably a discrepancy in what character(s) is used for the newline character. 

I made the change directly on github with the web-based file editor. Thought I could get away with a simple change like this without setting up a local environment, etc. 

If someone else could corrected and moved through, or give me some clear guidance on what I need to do, I'd really appreciate it. This bug is currently a critical roadblock to a project that is already running behind schedule for me.

**Comment by phillipskevin** [comment]
I think you might be able to fix it by changing the wrapping in the editor:
image

However, it might be a good idea to set up the repo locally anyway. It would be great if you could add a test for this case. It would basically be the same as the example you gave in the issue, but with an assertion (`ok(true, ...)`) in place of the `alert`.

**Comment by UselessPickles** [comment]
I tried running unit tests locally via "grunt test", but got this error:

Running "testee:steal" (testee) task
  Fatal error: spawn D:\DevProjects\github\canjs\node_modules\.bin\phantomjs ENOENT

Any ideas what I did wrong? This is on a windows 10 machine. I installed git, NodeJS, grunt-cli, cloned by canjs repo, checked out my "patch-1" branch, ran "npm install" and "bower install" in my repo directory. Am i missing a step?

For now I pushed my changes to see if my new unit test passes.

**Comment by UselessPickles** [comment]
Also, looks like I still have some whitespace issues, probably caused by an inconsistency between using space characters or tab characters for indentation. What's the standard for this project?

**Comment by UselessPickles** [comment]
Now that the tests have passed, is there any way to confirm that my new unit test actually executed? I can't find anything in the logs.

**Comment by phillipskevin** [comment]
We're using tabs. You can set up EditorConfig (http://editorconfig.org/) in your editor to make sure your spacing is correct.

Instead of using the grunt task to run the tests, you can just load one of the test pages in a browser (`test/jquery.html` for instance).

**Comment by UselessPickles** [comment]
@phillipskevin All indents converted from spaces to tabs. As far as I can tell, my new unit test should be executing and is passing, but I still am not sure where to look for some sort of log that confirms that the new test in batch_test.js file specifically was executed/passed.

**Comment by UselessPickles** [comment]
Is this ever going to be merged? If not, I'd like to close it to clean up my list of pending PRs.

**Comment by justinbmeyer** [comment]
I'll try to find someone to take a look at it tomorrow.  Thanks for being persistent!

**Comment by phillipskevin** [comment]
This is published in `can@2.3.34`.

**Pull request merged**
